name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: 'toolframework/toolframeworkapplication'
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: pwd && ls && ln -s ./ /ToolApplication/UserTools/ImportedTools/ToolPack 
        && cd /ToolApplication/UserTools/ImportedTools/ 
        && cd ToolPack 
        && pwd
        && ls
        && mv /usr/bin/dialog /usr/bin/dialogx 
        && ./Import.sh All
    - name: make
      run: cd ../../../
        && source Setup.sh
        && make clean
        && make
    - name: test
      run: ./main
